name: CICD

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: docker build -t echoech0/reactapp .
    
      - name: Publish Image to Docker Hub
        run: docker push echoech0/reactapp:latest 

    

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Delete Old Image
        run: docker rmi -f echoech0/reactapp

      - name: Pull Docker Image
        run: docker pull echoech0/reactapp:latest

      - name: Delete Old Container 
        run: docker rm -f reactContainer

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactContainer echoech0/reactapp
